api = "0.10"

[buildpack]
id = "heroku/nodejs-pnpm-engine"
version = "2.6.6"
name = "Heroku Node.js pnpm Engine"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js pnpm Engine buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["pnpm", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-pnpm-engine" }
