[package]
name = "test_support"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bon = "3"
insta = { version = "1", features = ["filters"] }
libcnb = "=0.30.2"
libcnb-test = "=0.30.2"
serde_json = "1"
tempfile = "3"
ureq = "3"
