api = "0.2"

[buildpack]
id = "heroku/nodejs-function"
version = "0.5.1"
name = "Node.js Function"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.7.3"

[[order.group]]
id = "heroku/nodejs-npm"
version = "0.4.3"

[[order.group]]
id = "heroku/nodejs-typescript"
version = "0.2.2"
optional = true

[[order.group]]
id = "heroku/nodejs-function-invoker"
version = "0.1.1"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack"
