api = "0.9"

[buildpack]
id = "heroku/nodejs-function"
version = "1.0.1"
name = "Node.js Function"
homepage = "https://github.com/heroku/buildpacks-nodejs"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "1.0.1"

[[order.group]]
id = "heroku/nodejs-npm"
version = "1.0.1"

[[order.group]]
id = "heroku/nodejs-function-invoker"
version = "1.0.1"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/heroku/buildpack-nodejs-function"
