api = "0.2"

[buildpack]
id = "heroku/nodejs-npm"
version = "0.4.0"
name = "NPM Buildpack"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata.release.docker]
repository="public.ecr.aws/r2f9u0w4/heroku-nodejs-npm-buildpack"
