api = "0.6"

[buildpack]
id = "heroku/nodejs-npm"
version = "0.5.3"
name = "NPM Buildpack"
homepage = "https://github.com/heroku/buildpacks-nodejs"
keywords = ["nodejs", "node", "npm"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-npm-buildpack"
