api = "0.2"

[buildpack]
id = "heroku/nodejs-npm"
version = "0.4.2"
name = "NPM Buildpack"

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-npm-buildpack"
