api = "0.2"

[buildpack]
id = "heroku/nodejs-yarn"
version = "0.1.3"
name = "Yarn Buildpack"
keywords = ["nodejs", "node", "yarn"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-yarn-buildpack"
