api = "0.10"

[buildpack]
id = "heroku/nodejs-pnpm-install"
version = "0.0.9999"
name = "Heroku Node.js pnpm install"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js pnpm install buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["pnpm", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-pnpm-install" }
