api = "0.9"

[buildpack]
id = "heroku/nodejs"
version = "0.6.6"
name = "Node.js"
homepage = "https://github.com/heroku/buildpacks-nodejs"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.8.22"

[[order.group]]
id = "heroku/nodejs-corepack"
version = "0.1.2"

[[order.group]]
id = "heroku/nodejs-pnpm-install"
version = "0.1.1"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.8.22"

[[order.group]]
id = "heroku/nodejs-corepack"
version = "0.1.2"
optional = true

[[order.group]]
id = "heroku/nodejs-yarn"
version = "0.4.3"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.8.22"

[[order.group]]
id = "heroku/nodejs-npm"
version = "0.5.3"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/heroku/buildpack-nodejs"
