api = "0.2"

[buildpack]
id = "heroku/nodejs"
version = "0.3.1"
name = "Node.js"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.7.3"

[[order.group]]
id = "heroku/nodejs-yarn"
version = "0.1.3"

[[order.group]]
id = "heroku/nodejs-typescript"
version = "0.2.2"
optional = true

[[order.group]]
id = "heroku/procfile"
version = "0.6.2"
optional = true

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.7.3"

[[order.group]]
id = "heroku/nodejs-npm"
version = "0.4.3"

[[order.group]]
id = "heroku/nodejs-typescript"
version = "0.2.2"
optional = true

[[order.group]]
id = "heroku/procfile"
version = "0.6.2"
optional = true

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack"
