api = "0.2"

[buildpack]
id = "heroku/nodejs"
version = "0.3.9"
name = "Node.js"
homepage = "https://github.com/heroku/buildpacks-nodejs"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.7.4"

[[order.group]]
id = "heroku/nodejs-yarn"
version = "0.1.8"

[[order.group]]
id = "heroku/procfile"
version = "0.6.2"
optional = true

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.7.4"

[[order.group]]
id = "heroku/nodejs-npm"
version = "0.4.4"

[[order.group]]
id = "heroku/procfile"
version = "0.6.2"
optional = true

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack"
