api = "0.9"

[buildpack]
id = "heroku/nodejs"
version = "1.1.4"
name = "Node.js"
homepage = "https://github.com/heroku/buildpacks-nodejs"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "1.1.4"

[[order.group]]
id = "heroku/nodejs-corepack"
version = "1.1.4"

[[order.group]]
id = "heroku/nodejs-pnpm-install"
version = "1.1.4"

[[order.group]]
id = "heroku/procfile"
version = "2.0.1"
optional = true

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "1.1.4"

[[order.group]]
id = "heroku/nodejs-corepack"
version = "1.1.4"
optional = true

[[order.group]]
id = "heroku/nodejs-yarn"
version = "1.1.4"

[[order.group]]
id = "heroku/procfile"
version = "2.0.1"
optional = true

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "1.1.4"

[[order.group]]
id = "heroku/nodejs-npm-install"
version = "1.1.4"

[[order.group]]
id = "heroku/procfile"
version = "2.0.1"
optional = true

[metadata]
[metadata.release]
[metadata.release.image]
repository = "docker.io/heroku/buildpack-nodejs"
