api = "0.6"

[buildpack]
id = "heroku/nodejs-function-invoker"
version = "0.3.0"
name = "Heroku Node.js Function Invoker"
clear-env = true
homepage = "https://github.com/heroku/buildpacks-nodejs"
keywords = ["nodejs", "node", "node.js", "javascript", "js", "function"]

[[licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.runtime]
package = "@heroku/sf-fx-runtime-nodejs@0.11.0"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-invoker-buildpack"
