api = "0.8"

[buildpack]
id = "heroku/nodejs-function-invoker"
version = "0.3.11"
name = "Heroku Node.js Function Invoker"
homepage = "https://github.com/heroku/buildpacks-nodejs"
keywords = ["nodejs", "node", "node.js", "javascript", "js", "function"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[metadata]
[metadata.runtime]
package_name = "@heroku/sf-fx-runtime-nodejs"
package_version = "0.14.1"
[metadata.release]
[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-invoker-buildpack"
