api = "0.2"

[buildpack]
id = "heroku/nodejs-engine"
version = "0.7.2"
name = "Node Buildpack"
keywords = ["nodejs", "node", "javascript"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-engine-buildpack"
