api = "0.2"

[buildpack]
id = "heroku/nodejs-typescript"
version = "0.2.1"
name = "TypeScript Buildpack"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-typescript-buildpack"
