api = "0.9"

[buildpack]
id = "heroku/nodejs-npm-install"
version = "1.1.6"
name = "Heroku Node.js npm Install Buildpack"
homepage = "https://github.com/heroku/buildpacks-nodejs"
keywords = ["node", "node.js", "nodejs", "javascript", "js", "npm", "install"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[metadata]
[metadata.release]
[metadata.release.image]
repository = "docker.io/heroku/buildpack-nodejs-npm-install"
