[package]
name = "available-parallelism"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
libcnb = { version = "=0.30.1", default-features = false }

[lints]
workspace = true
