[package]
name = "test_support"
version = "0.0.0"
description = "Test support functions for integration tests"
publish = false
edition = "2021"
rust-version = "1.66"

[dependencies]
libcnb-test = "0.11"
tempfile = "3.3.0"
ureq = "2.5.0"
