[package]
name = "test_support"
description = "Test support functions for integration tests"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
libcnb-data.workspace = true
libcnb-test.workspace = true
tempfile.workspace = true
ureq.workspace = true
