[package]
name = "test_support"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bon = "2"
libcnb = "=0.24.0"
libcnb-test = "=0.24.0"
serde_json = "1"
tempfile = "3"
ureq = "2"
