[package]
name = "test_support"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
insta = { version = "1", features = ["filters"] }
bon = "3"
libcnb = "=0.26.0"
libcnb-test = "=0.26.0"
serde_json = "1"
tempfile = "3"
ureq = "2"
